name = "leilao-ibesaj-api"
main = "worker.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "leilao-ibesaj-db"
database_id = "05552fe1-404c-4698-91fb-1ddc7922b52d"

[assets]
directory = "./public"
binding = "ASSETS"
